### ISSUE TITLE
Version 1.1.4 hangs after update

### ISSUE THREAD

**Issue by wollmers** [austrianredcross/stopp-corona-ios#7] opened 2020-05-02 16:57 UTC
## Description

iOS version 12.4.5 and 12.4.6 (latest)
iPhone 5s
Language DE

Had a previous version of Stopp Corona installed and successfully configured (autoupdate on, mic on). Don't remember which version.

The app autoupdated to version 1.1.4 (latest).

If opened it shows the screen "Willkommen" and hangs after clicking forward to the last screen "Einwilligungserklärung" with a grey (inactive) button "Fertig".

Deleting and reinstalling the app does not help.

Also updating iOS to 12.4.6 (latest), deleting the app and reinstalling does not change the behaviour.

The FAQ at [https://participate.roteskreuz.at/faq_stopp_corona_app/](https://participate.roteskreuz.at/faq_stopp_corona_app/) does not provide helpful information to solve the problem.

**Comment by uluckas** [comment] 2020-05-02 17:53
Hi @wollmers 
did you install from play store?

**Comment by wollmers** [comment] 2020-05-02 20:02
@uluckas I installed from the Apple App store as usual. That's the standard way on an iPhone.

"play" would be Android.

**Comment by wollmers** [comment] 2020-05-02 20:19
@uluckas 

How complicated would it be to build and debug the app myself? I have Xcode on MacOS Mojave 10.14.6 and an old iPhone 5. But no experience in coding swift. Looks like C++, Java and all the other reinventions of the wheel.

**Comment by uluckas** [comment] 2020-05-12 17:24
Sorry, i am working on both platforms. Mixed up play- and app store.
You can not build the app your self because the source code does not include the API keys to for your self built app to connect to our back end, our p2pkit account and others.

**Comment by wollmers** [comment] 2020-05-14 19:26
Version 1.2.1 still has the same issue.

**Comment by bastianh** [comment] 2020-05-23 22:06
We were never able to reproduce the issue. It is expected that the button is greyed out until you accept the terms on the page, but after that the button should work.

**Comment by wollmers** [comment] 2020-05-24 15:51
@bastianh OK, now I read your comment 3 times, because it sounds not logical in comparison to what I see on my iPhone.

My screen begins with "Einwilligungserklärung" and ends with "ausgetauscht." Then comes the greyed button "Fertig".

I do not see the checkbox "Ich stimme zu" without scrolling. How should I know that I have to scroll down, if the previous 5 screens used red buttons "weiter" in the same place? Now I got it, puzzling over the meaning of "accept" in your comment and playing around.

It's a serious usability issue. Misleading interface design. And it's also an issue of incomplete documentation & FAQ.

At least the update didn't work automatically.

**Comment by tomLadder** [comment] 2020-06-24 13:32
> @bastianh OK, now I read your comment 3 times, because it sounds not logical in comparison to what I see on my iPhone.
> 
> My screen begins with "Einwilligungserklärung" and ends with "ausgetauscht." Then comes the greyed button "Fertig".
> 
> I do not see the checkbox "Ich stimme zu" without scrolling. How should I know that I have to scroll down, if the previous 5 screens used red buttons "weiter" in the same place? Now I got it, puzzling over the meaning of "accept" in your comment and playing around.
> 
> It's a serious usability issue. Misleading interface design. And it's also an issue of incomplete documentation & FAQ.
> 
> At least the update didn't work automatically.

@wollmers Feedback from my side: You could have written that in a more friendly way. Probably not the best way to contribute to a project.

**Comment by wollmers** [comment] 2020-06-25 16:25
@tomLadder What exactly is the reason for your ad hominem comment?

**Comment by mitsuhiko** [comment] 2020-06-26 06:59
@wollmers can you still reproduce this on the version released today?

**Comment by wollmers** [comment] 2020-06-30 07:50
> @wollmers can you still reproduce this on the version released today?

1. opened the app: "Aktuelle Version herunterladen" (download current version), "Zum App Store"
2. in the app store shows "Version 2.0.2", and "needs iOS 13.5 or newer"
3. leave the store, try to update from iOS 12.4.7: says current installed is the newest. Hardware is iPhone 5s
4. Google for it: https://support.apple.com/de-de/HT201222 says, iOS 13.5 is only available for iPhone 6s
5. try update the Stopp Corona App anyway. Watching the progress icon it downloads completely, but does not install.
6. now the app hangs in step 1. (see above)

Seems there are new issues now with severity critical:

- update to 2.0.2 not possible on iPhone 5s
- app (1.2.1) now unusable, because of the version check

**Comment by bastianh** [comment] 2020-06-30 08:03
Yes... unfortunately the exposure framework from Apple is only available for iOS 13.5, so it's not possible to use the app on iPhone 5s anymore.

**Comment by wollmers** [comment] 2020-06-30 08:13
@bastianh So it will never be usable on iPhone 5s?

If so, the FAQ should be updated to mention it. 

And you can close this issue as unsolvable.

**Comment by mitsuhiko** [comment] 2020-06-30 12:30
Going to close this issue then. Unfortunately there is nothing that can be done here without changes on Apple's side.

**Closed by mitsuhiko** 2020-06-30 12:30 UTC
Labels: question
